### ISSUE TITLE
Develop a buy/sell recommendation system.

### ISSUE THREAD

**Issue by informrohit1** [rohitinu6/Stock-Price-Prediction#1]
Hi @rohitinu6 i have seen your project "stock-price-prediction" and as you mentioned the future work, i would love to contribute in developing a buy/sell recommendation system using clustering algorithm and also a UI using flask for user to interact. so, can we discuss further about the addition. 
thanks

**Comment by rohitinu6** [comment]
You can work on it.
Let me know if you need any kind of help.
All the best. 👍

**Comment by informrohit1** [comment]
Please add me as a collaborator in the repository, So that I can make a
branch and start working on it or something else I need to do, please
provide me the details on it.

**Comment by rohitinu6** [comment]
@informrohit1  It would be better to work on a new branch

**Comment by informrohit1** [comment]
Okay I have already started working on it and I will upload it to a new
branch once it gets done..
Thank you sir
