### ISSUE TITLE
Include Volume Weighted Average Price (VWAP)

### ISSUE THREAD

**Issue by spandana2004** [rohitinu6/Stock-Price-Prediction#124]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, there is no Volume Weighted Average Price (VWAP) calculation available in the application. VWAP is a key technical indicator used in stock analysis to assess the average price at which a stock is traded throughout the day, weighted by volume. Traders rely on VWAP to identify trends, making it a crucial missing feature in the app for users looking to perform advanced stock analysis. I'm frustrated when I cannot analyze the stock trends with VWAP, which limits the depth of the analysis.

### Proposed Solution

I propose adding a VWAP calculation feature to the stock price dataset. By integrating this feature, users will be able to perform more in-depth trend analysis and make more informed trading decisions.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

This feature can be computed using the formula:
![image](https://github.com/user-attachments/assets/3e740476-c5cc-4f72-bbfe-a34622b28e56)
Where "Typical Price" is the average of the stock's High, Low, and Close prices. The formula will be coded in python.

**Comment by rohitinu6** [comment]
@spandana2004 Please ensure to star the repo,
All the best

**Comment by spandana2004** [comment]
Can i know is an website deployed for this project or else i am happy to contribute by developing one.

**Comment by rohitinu6** [comment]
Sure, you can make a new issue for a website, I'll be happy to assign you

**Comment by kanishk128** [comment]
Hey is this issue closed?

**Comment by kanishk128** [comment]
Ok, so can I help with this issue?

**Comment by spandana2004** [comment]
@kanishk128 VWAP has been included for the project i am waiting for the admin to merge the pull request. I would be happy if u can include anything else for it.

**Comment by rohitinu6** [comment]
@spandana2004 , I appreciate your valuable contribution to the repo.
Please share this issue on the discord discussion grp, also you can talk to [Sanjay](https://www.linkedin.com/in/sanjay-k-v?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAABOfyDkB3o8LG-IXfkprrsXLsFqQQIcWG6s&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BP4QTNtINRWSCwDdB8LW1rQ%3D%3D) sir on LinkedIn
