### ISSUE TITLE
Data Collection and Preprocessing

### ISSUE THREAD

**Issue by Anjankumar26** [rohitinu6/Stock-Price-Prediction#13]
Dear @rohitinu6 ,

I hope you're doing well. I am reaching out to express my interest in taking on the responsibility of data collection and preprocessing for our stock buy and sell prediction system.

I believe that gathering and preparing accurate historical stock data is crucial for the success of our predictive model. I am eager to contribute my skills in data management and preprocessing to ensure we have clean and reliable data for our analysis.

If you could assign me this task, I would greatly appreciate it. Please let me know if there are any specific requirements or if we can discuss this in more detail.

Thank you for considering my request.

Best regards,

Anjan kumar
Contributor

**Comment by Rashmi885** [comment]
I have worked before on Data analysis, would like to contribute on this project

**Comment by DataWorshipper** [comment]
Dear @rohitinu6 
Hope you are doing well,I am reaching out to express you my interest in furthur refining the data preprocessing steps of the train data ,i have worked in data analysis before ,and i believe that some parts of the train data need better and detailed analysis.

Thank you for considering my request ,
Abhiraj Mandal
Contribuor

**Comment by rohitinu6** [comment]
@Anjankumar26 , any update?

**Comment by Anjankumar26** [comment]
can you just check two files i uploaded 
[SBIN_cleaned.csv](https://github.com/user-attachments/files/17290331/SBIN_cleaned.csv)
and a python file for EDA

**Comment by Yashwanth112004** [comment]
I hope you're doing well. I'm reaching out to express my interest in further refining the data preprocessing steps of the training data. I have also worked on Data Analysis. I would like to contribute this project.

Thank you for considering my request.

Best regards,
Puligilla Yashwanth
Contributor

**Comment by harsha25-v** [comment]
Can I please work on this project?
