### ISSUE TITLE
Comprehensive Data Insights Dashboard with EDA using Tableau

### ISSUE THREAD

**Issue by manikjain105** [rohitinu6/Stock-Price-Prediction#133]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I will develop a comprehensive dashboard using Tableau, alongside conducting a complete Exploratory Data Analysis (EDA). This will provide users with valuable insights and a clearer understanding of the data.

### Proposed Solution

I will use Tableau to create a dynamic dasherboard and also perform EDA

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I have recently worked on similar projects, which has allowed me to develop the necessary skill sets to contribute effectively to this project. I am confident that my experience will enable me to add value quickly and efficiently

**Comment by manikjain105** [comment]
Yes ,  i have cross verified , this is a unique idea

**Comment by rohitinu6** [comment]
@manikjain105 all the best,
please ensure to star the repo
