### ISSUE TITLE
Add Cross-Validation for Improved Model Evaluation

### ISSUE THREAD

**Issue by protham02** [rohitinu6/Stock-Price-Prediction#14]
The current implementation lacks cross-validation, which could lead to biased results. Implementing k-fold cross-validation would provide a better assessment of model performance and generalization.

**Comment by protham02** [comment]
can you please add tags gssos extended, hactoberfest, hactoberfest accepted, etc.

**Comment by Moses-Mk** [comment]
Assign this to me, i will work on the cross validation to assure the data is not biased, i will also add additional features that handle class imbalances in case they i notice them and regularization techniques to prevent overfitting the model. 

Looking forward,
Thanks
