### ISSUE TITLE
[BUG] Date index frequency not set and Non-invertible MA parameters

### ISSUE THREAD

**Issue by shristirwt** [rohitinu6/Stock-Price-Prediction#142]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The time series index lacks a frequency causing it to be ignored during forecasting. 
The initial MA parameters are unsuitable and the model uses zeros as starting values. 

![Screenshot 2024-10-19 204004](https://github.com/user-attachments/assets/cf79028b-cfbe-4fbe-9813-81b375006612)

### Steps to Reproduce

Include any relevant details like:

- I was on page ARIMA_V2
- While executing the code I encountered the errors
- The date index had no frequency associated with it so it was ignored in forecasting . Also there were non-invertible MA parameters so it used zeros as starting parameters

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

I will associate a frequency with the date index and enforce invertibility to False for non - invertible MA parameters

**Comment by jvedsaqib** [comment]
Hello @shristirwt,

It seems that there is an issue with pushing LFS objects to the public fork on GitHub. To resolve this, I suggest uploading your model (the .pkl file) to Kaggle and providing the link here. This will allow us to access the model without facing these restrictions.

Let me know if you need assistance with the upload process.

**Comment by shristirwt** [comment]
@jvedsaqib Can you please elaborate that how can I complete it and where do I have to provide the link . How will I merge then ?

**Comment by jvedsaqib** [comment]
> @jvedsaqib Can you please elaborate that how can I complete it and where do I have to provide the link . How will I merge then ?
> 
> I uploaded the code on kaggle and this is the link https://www.kaggle.com/code/shristirwt/arima-v2

@shristirwt On the Models section upload your model
After that provide the link in your notebook and change your link access to public

**Comment by shristirwt** [comment]
@jvedsaqib I tried to upload the model 
Can you check it once?
https://www.kaggle.com/code/shristirwt/notebook76a22044a1/notebook

**Comment by jvedsaqib** [comment]
> @jvedsaqib I tried to upload the model Can you check it once? https://www.kaggle.com/code/shristirwt/notebook76a22044a1/notebook

Change the link access to public

**Comment by shristirwt** [comment]
> > @jvedsaqib I tried to upload the model Can you check it once? https://www.kaggle.com/code/shristirwt/notebook76a22044a1/notebook
> 
> Change the link access to public

@jvedsaqib I have changed the link access to public

**Comment by jvedsaqib** [comment]
@shristirwt 

![image](https://github.com/user-attachments/assets/e104c166-3494-4cf5-910f-4a3179ee06e4)

Upload your model here, after that

![image](https://github.com/user-attachments/assets/331065ea-2fb6-4da3-8896-ab47a3ff13b1)

You can share the link of your model where it is required to `load` the pkl file

Then cut the pkl file from your local branch as it is not needed to be pushed.

I hope this works !

**Comment by jvedsaqib** [comment]
@shristirwt untrack lfs object
if possible remove it

**Comment by shristirwt** [comment]
> @shristirwt untrack lfs object if possible remove it

@jvedsaqib Thank you so much for your help and time . With your help I am able to make a pull request . I came to know about new things.

**Comment by jvedsaqib** [comment]
> > @shristirwt untrack lfs object if possible remove it
> 
> @jvedsaqib Thank you so much for your help and time . With your help I am able to make a pull request . I came to know about new things.

Your welcome !
And Thanks for the contribution
