### ISSUE TITLE
Incorporate feature engineering for enhanced model performance 

### ISSUE THREAD

**Issue by AnsharaFayazBeigh** [rohitinu6/Stock-Price-Prediction#16]
Hello ! @rohitinu6 

I can add another layer of feature engineering where derived features are created from the existing data. 
I am suggesting technical indicators like SMA or EMA. Since the algorithms use random forest and LSTM, it would work well. 

Currently, I am learning about these and implementing these would help!

Can you please assign me this?

Contributor (GSSoc extended)

**Comment by AnsharaFayazBeigh** [comment]
@rohitinu6 
I am working on it! 
Meanwhile, could you also assign the necessary labels( level, hacktoberfest)?

**Comment by rohitinu6** [comment]
@AnsharaFayazBeigh done
