### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by jvedsaqib** [rohitinu6/Stock-Price-Prediction#168]
As now there is a webpage for the project
So the image at the top of the readme can be changed and also steps are needed on how to run the webpage using flask.

@rohitinu6 you can assign someone at FCFS

Thank you

**Comment by Karthik3904** [comment]
"Hi @rohitinu6,
I’d like to take on this issue. Here’s my proposed solution:

Enhancing the Project Title: I will update the project’s title in the README.md to a more attractive, centered format using custom styling (such as bold and emojis for better visuals).

Adding the GIF: I will replace or enhance the current image with a GIF that showcases the project’s functionality. The GIF will be centered in the README.md for better presentation.

Let me know if I can proceed! Thank you."
