### ISSUE TITLE
Modify the AUTHOR section

### ISSUE THREAD

**Issue by alo7lika** [rohitinu6/Stock-Price-Prediction#183]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The current "AUTHOR" section in the README does not clearly present the contributors or lacks certain relevant details. The section could be enhanced to provide a more organized and visually appealing display of the author(s) with additional context if needed.

### Relevant Details
- **What page you were on:** README file in the repository.
- **What you were trying to do:** Understand the contributors' information in the AUTHOR section.
- **What went wrong:** The section appeared cluttered or lacked visual clarity, making it difficult to quickly identify contributors.

### Screenshots

N/A

### Do you want to work on this issue?

Yes

### Steps to Reproduce
1. Open the README file of the repository.
2. Scroll down to the "AUTHOR" section.
3. Observe the current format and content.
4. Notice the areas that could be improved for clarity or visual appeal.

### Expected Behavior
- A more organized presentation of the AUTHOR section.
- Visual elements like images or badges could be added.
- Clear and concise details about each author or main contributor.
- Links to the contributors' profiles for better accessibility.

**Comment by alo7lika** [comment]
@rohitinu6 assign me the task under GSSOC ext 24 And HACKTOBERFEST. (LEVEL 2 if possible)

**Comment by rohitinu6** [comment]
@alo7lika this issue is quite similar to the PR #182 , which you have contributed, please do not spam.
Try making changes in this pr, will assign the level accordingly
