### ISSUE TITLE
Clustering Algorithms for Buy/Sell Recommendation System

### ISSUE THREAD

**Issue by kundana29** [rohitinu6/Stock-Price-Prediction#19]
The project currently outlines various regression algorithms for stock price prediction but lacks a detailed approach to developing a buy/sell recommendation system using clustering algorithms. Implementing a recommendation system can significantly enhance trading strategies by suggesting optimal buying and selling points based on historical stock behavior and patterns.
please assign this issue to me

**Comment by rohitinu6** [comment]
@kundana29 all the best

**Comment by alo7lika** [comment]
i would love to contribute to this project @rohitinu6  Assign me this project

**Comment by rohitinu6** [comment]
@kundana29 , any upate?

**Comment by kundana29** [comment]
@rohitinu6 i am working on it . i will update you soon
