### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by piyush182004** [rohitinu6/Stock-Price-Prediction#2]
Can I add few more algorithms?like lightgbm,catboost,arima etc

**Comment by rohitspace11** [comment]
i want to add this algorithm 
Ridge Regression: A regularized version of linear regression, useful for multicollinearity.
Lasso Regression: Another regularization technique that can help with feature selection.
ElasticNet: A hybrid of Ridge and Lasso.
Bayesian Ridge Regression: Incorporates probabilistic predictions.
CatBoost: Another powerful gradient boosting algorithm.
LightGBM: An efficient gradient boosting algorithm.
ExtraTreesRegressor: A more randomized version of Random Forest.
please assign task to me

**Comment by Jashwanthallenki** [comment]
Yes you can add, and it is compulsory to test the accuracy with different algorithms

From past few months i have explored many algorithms
So i think i can test with many algorithms,

**Comment by rohitspace11** [comment]
here labels and work not assign to anyone

**Comment by rohitinu6** [comment]
@piyush182004 all the best

**Comment by rohitinu6** [comment]
@Jashwanthallenki and @rohitspace11 , I appreciate your curiosity to this repository, so I encourage you to come up with a new idea.
All the best

**Comment by Jashwanthallenki** [comment]
Yeah  done

**Comment by BlossomBreeze25** [comment]
I want t contribute , can i ?

**Comment by rohitinu6** [comment]
@piyush182004 , any update?

**Comment by piyush182004** [comment]
@rohitinu6 yeah will update before sunday

**Comment by piyush182004** [comment]
Please check made my pull request.
