### ISSUE TITLE
Removal of Classification Metrics from Regression Model Evaluation

### ISSUE THREAD

**Issue by AYUSHI-SHA** [rohitinu6/Stock-Price-Prediction#22]
Hi, I’ve also noticed that the evaluation of the regression model includes classification metrics such as accuracy, precision, recall, F1 score, and confusion matrix. These metrics are specifically designed for classification tasks where the goal is to predict discrete labels. However, in project which involves Stock Price Prediction which is a regression tasks, the objective is to predict continuous values, making these metrics irrelevant and potentially misleading when evaluating model performance.

Since metrics like Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and Mean Absolute Percentage Error (MAPE) are already implemented and are appropriate for this regression task, I suggest removing the classification metrics. This will help maintain clarity and focus on relevant performance indicators.

If you agree with this proposal, please assign this issue to me and label it accordingly. I'd be happy to work on the changes.

Thanks for your consideration!

**Comment by AnujSaha0111** [comment]
Can you please assign it to me @rohitinu6 @sanjay-kv

**Comment by rohitinu6** [comment]
@AYUSHI-SHA , any update?

**Comment by AYUSHI-SHA** [comment]
@rohitinu6 Sir I have already made the changes 2 days ago and raised a PR with 2 commits and it was merged succesfully. The changes are being reflected on the original code.
I only forgot to mention the fixes. 
I request you to close this issue if you see it as solved or I can raise another PR for the same to mention the fixes and close it automatically when merged.

**Comment by AYUSHI-SHA** [comment]
![image](https://github.com/user-attachments/assets/1ccffc23-cb0d-428c-a9e7-d235db8843e7)
@rohitinu6
