### ISSUE TITLE
Suggestions for Improving the README File

### ISSUE THREAD

**Issue by AYUSHI-SHA** [rohitinu6/Stock-Price-Prediction#23]
I've been going through the project's README file and would like to suggest a few changes that could enhance clarity and better align with the project's objectives, particularly since this is a regression-based stock price prediction project. Here are my recommendations:

1. **Inconsistent Focus on Classification Algorithms:** The README states, "Utilizes various classification algorithms for stock price prediction," which could confuse readers, as stock price prediction is fundamentally a regression task. I recommend changing this to:
"Utilizes various regression algorithms for stock price prediction."

2. **Irrelevant Classification Metrics (Precision and Recall)**: Precision and recall are metrics used in classification and are not applicable to a regression task. These should be removed from the Results section, with a focus instead on regression metrics like RMSE, MAE, and MAPE.

3. **Clarification of Algorithm Results**: In the Results section, the term "accuracy" is mentioned when discussing regression performance. Since accuracy is generally a classification metric, it would be more appropriate to replace it with a term like "performance," or to concentrate directly on the metrics used (e.g., RMSE, MAE).

4. **Typographical Errors**: There are a few typographical errors, such as "Algortihms" instead of "Algorithms" and "Clustering algorithsm" instead of "Clustering algorithms." Correcting these would improve readability.

5. **Improved Explanation in Results**: The explanation of algorithm performance could benefit from more detail. For instance, elaborating on why certain algorithms exhibit unusually high RMSE would provide readers with better insights and strengthen the final recommendations.

If these suggestions resonate with you, assign the task to me and mark the appropriate labels. I would be glad to make the necessary edits.

**Comment by Teja-m9** [comment]
Hey assign this task to me @sanjay-kv

**Comment by AnujSaha0111** [comment]
@rohitinu6 @sanjay-kv Can you please assign it to me. I want to work on the issue

**Comment by sanjay-kv** [comment]
@Teja-m9 im not admin of this project, I can only manage any improper labels.
