### ISSUE TITLE
Adding more evaluation metrics 

### ISSUE THREAD

**Issue by ramana2074** [rohitinu6/Stock-Price-Prediction#3]
I've seen the project, and it would be better if more evaluation metrics are added such as R-squared, Mean squared logarithmic error (MLSE) and coefficient of variation to evaluate the performance of the algorithms.

**Comment by rohitinu6** [comment]
@Varun-malviya5  I appreciate your curiosity to this repository, so I encourage you to come up with a new issue.
All the best
