### ISSUE TITLE
To add more charts for better understanding.

### ISSUE THREAD

**Issue by SimranShaikh20** [rohitinu6/Stock-Price-Prediction#33]
@rohitinu6 
Hi, I am Simran Shaikh. I’ve been reviewing the project as part of my contribution to GSSoC Extended 24 and noticed that the code performs  by adding more charts for better understanding we can used different library  of python like seaborn  or matplotlib . By using this library its easy to understand stock prediction . Also we can include some data cleaning concept for more accurate and efficient data. 

This would help increase in more visualization . I would like to work on this.
If you like this idea, please assign the task to me and add the corresponding charts to it.
Thank you for your time and consideration!

**Comment by SimranShaikh20** [comment]
@rohitinu6  can you please me assign me again there is some issue i am not able access it .

**Comment by shradiphylleia** [comment]
can you assign me this issue. I would try to add in a report to mark the probable predictors

**Comment by SimranShaikh20** [comment]
@rohitinu6 check the pr request and let me know is there any changes or conflicts are there.

**Comment by rohitinu6** [comment]
@SimranShaikh20 , thank you for your valuable contribution, your pr will soon be reviewed by the mentors.
Till then, please ensure you star the repo
