### ISSUE TITLE
Removal of Classification Metrics from Regression Model Evaluation

### ISSUE THREAD

**Issue by AnujSaha0111** [rohitinu6/Stock-Price-Prediction#35]
I’ve also noticed that the evaluation of the regression model includes classification metrics such as accuracy, precision, recall, F1 score, and confusion matrix. These metrics are specifically designed for classification tasks where the goal is to predict discrete labels. However, in project which involves Stock Price Prediction which is a regression tasks, the objective is to predict continuous values, making these metrics irrelevant and potentially misleading when evaluating model performance.

Since metrics like Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and Mean Absolute Percentage Error (MAPE) are already implemented and are appropriate for this regression task, I suggest removing the classification metrics. This will help maintain clarity and focus on relevant performance indicators.

**Comment by AnujSaha0111** [comment]
Can you please assign me the issue?

**Comment by AnujSaha0111** [comment]
Issue is solved in https://github.com/rohitinu6/Stock-Price-Prediction/pull/37

**Comment by rohitinu6** [comment]
@AnujSaha0111 Thank you for your valuable contribution, Please mention this issue number in the description of your PR.
Only those PR, that solve an existing issue will be considered for evaluation by the mentors.

**Comment by AnujSaha0111** [comment]
Done👍

**Comment by AnujSaha0111** [comment]
Was it merged?
