### ISSUE TITLE
Train ARIMA (Autoregressive Integrated Moving Average) for stock predition

### ISSUE THREAD

**Issue by DarshAgrawal14** [rohitinu6/Stock-Price-Prediction#41]
Hello @rohitinu6,
I'm Darsh Agrawal, a fellow contributor. I'm interested in working on stock prediction using the ARIMA (Autoregressive Integrated Moving Average) model. ARIMA is a statistical method for time series analysis that can be applied to stock prediction tasks.
If you think this approach aligns with the project goals, I would appreciate being assigned to this task.

**Comment by rudraksh2611** [comment]
Hello @rohitinu6 sir, 
My name is Rudraksh Singh Bhadauria and I’d love to jump in on the "Train ARIMA for stock prediction" project! I’ve worked with time series data before with DRDO and have experience using ARIMA models with Python. I think I can bring some useful skills to the table and really help move this forward. I’m excited about the challenge and eager to contribute. 
Would you mind assigning me to the project? 
Thanks a lot!

**Comment by DarshAgrawal14** [comment]
I have trained an ARIMA model but accuracy is not that good , so i am currently working on combining ARIMA with LSTM and check the accuracy of hybrid model ,need a little bit more time

**Comment by DarshAgrawal14** [comment]
@rohitinu6  I have submitted the PR , and mentioned the changes if anything else please let me know
