### ISSUE TITLE
Eliminate Mounting Google Drive for Datasets and Tuning

### ISSUE THREAD

**Issue by Aarathi1535** [rohitinu6/Stock-Price-Prediction#42]
In the code, the datasets are being mounted from google drive which takes more time and lags execution time. Instead the datasets are present in Data directory so fetching from it will be more feasible.
Also, all the machine learning algorithms are implemented with default parameters, we can tune them by changing the paramenters to improve accuracy. Moreover, extra algorithms like Logistic Regression, Naive Bayes etc can also be implemented to improve model performance.

I am a GGSoC Ext '24 Contributor. Kindly assign this issue to me for fixing.

A kind request to add (gssoc-ext) and (hacktoberfest-accepted) as labels.

**Comment by ModZ777** [comment]
Here we apply tuning test for the verification of the ML model for the issues given.
please assign this issue to me.
