### ISSUE TITLE
[BUG] Enable the code to run both on google colab as well as local system

### ISSUE THREAD

**Issue by shristirwt** [rohitinu6/Stock-Price-Prediction#47]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

I found that the code displays an error if not executed on google colab hence I want to modify it so that it runs both on google colab as well as local environment
![Screenshot 2024-10-05 165809](https://github.com/user-attachments/assets/ad3933d7-8c7b-4a0b-80d9-57ec56e90eb7)

### Steps to Reproduce

Include any relevant details like:

- I found the error on Stock_Price_Prediction.ipyng
- I was executing the code when I found the error
- It displayed an error saying No module named google.colab

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

I will check if the code is being executed on google colab or on the local system and then the path of the file will be provided accordingly

**Comment by jvedsaqib** [comment]
Hi @shristirwt,

I have reviewed the code, and it is functioning as expected on my end. 
Could you please verify if you are using the correct path?

![image](https://github.com/user-attachments/assets/ac09bc25-cf8b-401e-bfe1-a46e9cb8db7a)

Let me know if you encounter any issues or need further assistance.

**Comment by shristirwt** [comment]
Hello @jvedsaqib ,
I am running the code locally that's why it is resulting in an error . I was thinking of implementing the code in a way that it runs on both
![Screenshot 2024-10-05 191058](https://github.com/user-attachments/assets/a552778f-7279-446e-b195-b3b7ad8d830a)

**Comment by jvedsaqib** [comment]
Ok! 
If you are running locally then there's no need to import colab. You can just load the DS directly.
As for changing it to be flexible for both ways, it would be great.
@rohitinu6 can assign you to this.

**Comment by shristirwt** [comment]
Thank you

Do I need to reach out to him or will he assign it to me from the issues raised
