### ISSUE TITLE
File structure - redundant files

### ISSUE THREAD

**Issue by jvedsaqib** [rohitinu6/Stock-Price-Prediction#49]
Hi @rohitinu6 
Raising this issue as there are two notebooks and csv files. It might make things confusing.
Please assign someone to resolve this

**Comment by Moses-Mk** [comment]
Please elaborate on this issue, I will pick it up. Thanks

**Comment by ABHINAV2087** [comment]
Hi @rohitinu6 
i want to pick up this issue and want to resolve it please assign it to me

**Comment by jvedsaqib** [comment]
@ABHINAV2087 
Check the file structure, there's two ipynb files. 
1st at the main directory and 2nd inside Python File
They both are actually same
Some contributors are changing 1st notebook while others are using 2nd notebook
