### ISSUE TITLE
[FEATURE] PCA-Principal Component Analysis

### ISSUE THREAD

**Issue by shradiphylleia** [rohitinu6/Stock-Price-Prediction#52]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Feature Engineering would allow to better understand the attribute of the dataset.

- [ ]  New features which improve the predictability could be derived
- [ ] Dimensionality reduction 

### Proposed Solution

Perfrom principal component analysis to support the model building efforts

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Perform descriptive analysis and standard PCA techniques to achieve the goal of the issue

**Comment by Mukunj-21** [comment]
I would like to work on this , kindly assign me this issue @rohitinu6
