### ISSUE TITLE
[SMA Indicator] <We can add a SMA indicator in the dataset as it may give a better intuition about the trends and may also improve model improvements >

### ISSUE THREAD

**Issue by Pankaj4152** [rohitinu6/Stock-Price-Prediction#56]
### Is this a unique feature?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current dataset doesn't give a better intuition of the trend of the market

### Proposed Solution

Can add a SMA indicator

### Screenshots

before - 
![image](https://github.com/user-attachments/assets/bb7a9cf5-5fe8-4b98-95f8-b79b757c7ab3)
after- 
![image](https://github.com/user-attachments/assets/93d28296-7dc5-4a9f-895a-b70f61ba203b)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Can add SMA indicator by taking average of last 10 and 50 days Close price for SMA 10 and SMA 50 .

@rohitinu6 Can you please assign me this?

**Comment by rohitinu6** [comment]
@Pankaj4152 sure, please ensure you star the repo, All the best
