### ISSUE TITLE
[BUG] Mismatched Feature Names in Model Prediction

### ISSUE THREAD

**Issue by shristirwt** [rohitinu6/Stock-Price-Prediction#57]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The feature names in model prediction are mismatching. It is resulting in a warning message.
![Screenshot 2024-10-06 082827](https://github.com/user-attachments/assets/a23d535b-8c52-4d18-a565-23fadf3a0437)
![Screenshot 2024-10-06 082851](https://github.com/user-attachments/assets/179b75ab-025f-4244-ac74-4a029f407ac0)
![Screenshot 2024-10-06 082910](https://github.com/user-attachments/assets/f4371190-acd7-4d1b-8a4e-552f3a716a74)

### Steps to Reproduce

Include any relevant details like:

- I was on Stock_Price_Prediction.ipynb
- I was executing the code when I came across this warning message .
- It was displaying an error message for mismatching of feature names.

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

I will provide the model the required number of features so that it predicts properly

**Comment by rohitinu6** [comment]
@shristirwt , pls ensure u star the repo, all the best

**Comment by shristirwt** [comment]
Dear @rohitinu6 , 
You did not add the level in the labels
