### ISSUE TITLE
[RSI Indicator] <We can add a RSI indicator in the dataset as it may give a better intuition about the trends and may also improve model improvements >

### ISSUE THREAD

**Issue by Pankaj4152** [rohitinu6/Stock-Price-Prediction#59]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current dataset doesn't give a better intuition of the trend of the market

### Proposed Solution

Can add a RSI indicator

### Screenshots

before-
![image](https://github.com/user-attachments/assets/0d142d74-2f7a-474c-99bc-1d20d48f96eb)
after-
![image](https://github.com/user-attachments/assets/ebfcf485-27b5-47fb-bc5d-e222561266ef)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Can add RSI indicator by using its formula:  RSI = 100 - (100- (1 + avg gain/avg loss)).
@rohitinu6 Can you please assign me this?

**Comment by jvedsaqib** [comment]
@Pankaj4152 can you also add a plot to visualize it?

**Comment by Pankaj4152** [comment]
> @Pankaj4152 can you also add a plot to visualize it?

yeh good idea i will try.
