### ISSUE TITLE
[FEATURE] Deploying the Site

### ISSUE THREAD

**Issue by Monu2114** [rohitinu6/Stock-Price-Prediction#66]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Yes . Currently the app isnt deployed on any site

### Proposed Solution

To deploy the model on streamlit

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I would learn from online how to deploy sites on vercel and then implement the features of this site on streamlit

**Comment by shyamyellapu** [comment]
i want to work on this issue .
i will deploy this using streamlit in the huggingface

**Comment by rohitinu6** [comment]
@Monu2114 , please ensure you star this repo
All the best

**Comment by rohitinu6** [comment]
@shyamyellapu , appreciate your curiosity to this repo, please come up with a new issue and do ensure to star this repo.
All the best
