### ISSUE TITLE
occupying more memory space by each algorithm 

### ISSUE THREAD

**Issue by VivekShahare04** [rohitinu6/Stock-Price-Prediction#7]
@rohitinu6 
Each and every model is trained perfectly its great! @rohitinu6 
report for every model is great accuracy, score, rmse, etc.

but I think every model is taking their specific memory to train model and it will take more time as well as space ,
i think an loop should be include to calculate report as well as prediction value by each algorithm...

so here i am attaching an text document if you like it? please let me know i will just add it up.. @rohitinu6 
[stockprice.txt](https://github.com/user-attachments/files/17214382/stockprice.txt)

**Comment by VivekShahare04** [comment]
Currently I am working on your future idea of sentiment analyse one its an great idea @rohitinu6 
i am very excited to work with u on this project ..let's do it ....

can we?

**Comment by rohitinu6** [comment]
@VivekShahare04 sure, all the best

**Comment by VivekShahare04** [comment]
Rohit actually my virtual environment is not working can you provide me how
to setup this repository or i already added text file in previous mail
please look into it.
