### ISSUE TITLE
Refactor Redundant Printing Statements in Model Evaluation

### ISSUE THREAD

**Issue by spandana2004** [rohitinu6/Stock-Price-Prediction#71]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The current implementation of the model training and evaluation process includes repeated printing statements for both training and evaluation metrics across different models. This redundancy can lead to difficulties in maintaining the code and may clutter the output.

### Proposed Solution

To streamline the code, I suggest creating a single function that handles the printing of evaluation metrics. Additionally, we can utilize a loop to process each model, reducing redundancy and improving code readability.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

Steps to Reproduce:
Review the current implementation of the model training and evaluation process.
Observe the repeated printing statements for each model's metrics.
Implement the proposed solution to refactor the code.

@rohitinu6 can u pls assign this to me?

**Comment by spandana2004** [comment]
Can u pls let me know if the pull request was successful?

**Comment by rohitinu6** [comment]
@spandana2004 , Please ensure you star this repo

**Comment by spandana2004** [comment]
ok sir.

**Comment by jvedsaqib** [comment]
@spandana2004 can you provide any screenshot before I merge your PR?
