### ISSUE TITLE
Improving the visualization graphs!

### ISSUE THREAD

**Issue by isnehamondal** [rohitinu6/Stock-Price-Prediction#8]
I am Sneha Mondal, contributor in GSSoC'24.

ISSUE: 
There are a lot of graphs all together and as a viewer, sometimes its difficult to continuously move to check each and every and consume time.. and also there are 10 algorithms. 

WHAT I CAN DO?
I can make the visualization better using different visualization tools and also import or use other things if required, in the following manner:
1) combining the accuracy and precision of all 10 together which brings down two different graphs to one
2) since you mentioned 2, 6, 8, 10 have the highest accuracy so, based on that we can look forward to other evaluation metrics and make a graph for its metrics combining those 4 together and hence, it will help to finally come down to the last conclusion that you got and it will be easily understood.

I would like to work on this. If you like this idea, please assign this task to me and add the corresponding labels to it.

**Comment by rohitinu6** [comment]
@isnehamondal all the best, will add the labels
