### ISSUE TITLE
[FEATURE] Merging notebooks in one while maintaining all the code.

### ISSUE THREAD

**Issue by jvedsaqib** [rohitinu6/Stock-Price-Prediction#80]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

As there are so many notebooks present.
Please try to merge all in one place.
Maintain proper markdowns and comments to let other contributors know how to add or remove cells.
By doing this we will get a clean and well defined notebook.

### Proposed Solution

1 - Check all the notebooks and get a clear idea of everything.
2 - Create a notebook and divide sections (also subsections if required)
3 - Do proper comments and markdowns
4 - Make sure the code works

NOTE - 
Try to comment in places where each contributor changes the code (i.e. DATASET loading path).

### Do you want to work on this issue?

No

**Comment by Pankaj4152** [comment]
@rohitinu6 or @jvedsaqib can you assign me this?

**Comment by Pankaj4152** [comment]
while getting the model performance parameters which should I have in the combined one-

1st![image](https://github.com/user-attachments/assets/c7cdec26-b487-4225-bd91-5311b9faad2a)
 or 
2nd 
![image](https://github.com/user-attachments/assets/1e0aaed8-8e32-4539-980f-0c413634bd2c)

@rohitinu6 
@jvedsaqib
