### ISSUE TITLE
[Graph] <Indicator Graphs>

### ISSUE THREAD

**Issue by Pankaj4152** [rohitinu6/Stock-Price-Prediction#83]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Current Indicator graphs are too much compressed in a long period of time so we can limit its range and ask user that of how many past days he wants to see indicators with price graph and then it will display accordingly.

will improve user experience to see and analyze the price more and be more sure of price prediction and can verify also.

@rohitinu6 or @jvedsaqib can you assign me this and please suggest some suggestion if have any like can use seaborn library to make graphs more interactive or instead of asking from user we can set it default to past 100 days. and what else can i do?

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Screenshots

before-
![image](https://github.com/user-attachments/assets/51ed214f-40ee-432f-b345-97602a021b39)
![image](https://github.com/user-attachments/assets/3be1e4a5-b155-4355-8778-da75a0304af7)
![image](https://github.com/user-attachments/assets/c4f67f31-6e9f-47a3-a05b-564f9f6423db)

after- past 100 days
![image](https://github.com/user-attachments/assets/acb825a7-d208-48a7-af5c-cb9db2f129f1)
![image](https://github.com/user-attachments/assets/2275308a-4d80-4737-93f4-9e03a3afc4c0)
![image](https://github.com/user-attachments/assets/d3f490e0-0e97-41fb-94cb-d9bc05c98ac2)

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this.

can ask for user of past how many days and while plotting  the graph access only the last few days data instead of all data to plot graph.

**Comment by rohitinu6** [comment]
@Pankaj4152 , great work
Since you have solved a lot of issues in this repo, I believe you are now very well acquainted with this project, can you please go through issue no. #80 and let me know if you can resolve it at the earliest possible.

**Comment by Pankaj4152** [comment]
> @Pankaj4152 , great work Since you have solved a lot of issues in this repo, I believe you are now very well acquainted with this project, can you please go through issue no. #80 and let me know if you can resolve it at the earliest possible.

Sure I will try you can assign me that

**Comment by Pankaj4152** [comment]
> > @Pankaj4152 , great work Since you have solved a lot of issues in this repo, I believe you are now very well acquainted with this project, can you please go through issue no. #80 and let me know if you can resolve it at the earliest possible.
> 
> Sure I will try to do it by tomorrow morning. You can assign me that
