### ISSUE TITLE
Create plots for the predicted values

### ISSUE THREAD

**Issue by deepanshubaghel** [rohitinu6/Stock-Price-Prediction#99]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, the project does not provide visualizations for the predicted values of the models. This absence makes it difficult to assess how well the models are performing in terms of predicting the target variable compared to the actual values. By adding plots for predicted values, users will be able to visually compare the models’ outputs against the actual data, enhancing the interpretability and trust in the model's predictions.

### Proposed Solution

I propose to implement visualization plots that display the predicted values against the actual values for each regression model used in the project. This will involve creating line plots for a sample of the predicted values versus the actual values over time, which will provide insights into how well the models are capturing the underlying patterns in the data.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To enhance model evaluation, modify the evaluation function to return predicted values, create a visualization function to plot actual vs. predicted values, and integrate this visualization for all models, providing clear insights into prediction accuracy and model performance.

Please assign me this issue .
@rohitinu6

**Comment by Mukunj-21** [comment]
I would like to work on this , please assign me this issue @rohitinu6

**Comment by dimeneman** [comment]
I also want to  work on this , please assign me this issue @rohitinu6
